import { z } from 'zod'

export const EcommerceValidation = {
  // --- VARIANT ---
  variant: {
    create: z.object({
      name: z.string().min(1, 'Name is required'),
      options: z.array(z.object({
        label: z.string().min(1),
        value: z.string().min(1),
        image: z.any().optional()
      })).min(1, 'At least one option required'),
      showImage: z.boolean().optional(),
      order: z.number().optional(),
      desc: z.string().optional()
    }),
    update: z.object({
      name: z.string().optional(),
      options: z.array(z.any()).optional(),
      showImage: z.boolean().optional(),
      order: z.number().optional(),
      desc: z.string().optional()
    }).partial()
  },

  // --- STOCK (Read/Init) ---
  stock: {
    // Usually generated by system, but for manual init:
    create: z.object({
      productId: z.string().min(1),
      warehouseId: z.string().min(1),
      variantCombination: z.array(z.string()).default([]),
      sku: z.string().min(1),
      price: z.number().min(0),
      priceImport: z.number().optional(),
      priceSale: z.number().optional(),
      quantity: z.number().default(0), // Initial quantity
    })
  },

  // --- TRANSACTION (The main action) ---
  transaction: {
    create: z.object({
      productId: z.string().min(1),
      warehouseId: z.string().min(1),
      stockId: z.string().optional(), // If known, else search by product+warehouse+variant
      variantCombination: z.array(z.string()).optional(), // Required if stockId missing

      type: z.enum(['import', 'export', 'adjust']),
      quantity: z.number().min(1, 'Quantity must be positive'),
      price: z.number().min(0).optional(), // Price per unit
      note: z.string().optional()
    })
  }
}
